version: '3'

services:
  db:
    restart: always
    image: postgres
    container_name: db
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  run_migrations:
    build: .
    env_file: ./.env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  backend:
    build: .
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata db.json
      && python manage.py loaddata db1.json
      && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./.env.docker/:/app/.env

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/var/lib/redis

  celery:
    container_name: celery
    build: .
    command: >
      bash -c "celery -A config worker --beat --loglevel=info"
    volumes:
      - .:/app
      - ./.env.docker:/app/.env
    links:
      - redis
    depends_on:
      - redis
      - backend

volumes:
  pgdata: