# Generated by Django 4.2.3 on 2023-08-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=7000, verbose_name='стоимость курса'),
        ),
    ]
