# Generated by Django 4.2.3 on 2023-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='id_stripe',
            field=models.CharField(blank=True, null=True, verbose_name='id'),
        ),
    ]
